### ISSUE TITLE
Open new files from the list not working as expected

### ISSUE THREAD

**Issue by koansoftware** [oleg-shilo/Favorites.vscode#13]
Your extension is the closest extension to the feature I need.
It's awesome, thank you !

The popup menu option "Open new files from the list" is not working as expected, because opens only the selected file.
I'd suggest to have two different options:

- Open selected file
- Open all files in the list
 
Thank you

**Comment by oleg-shilo** [comment]
Makes sense. Agree.

Though there is something strange about it.

The context menu "Open new files from the list" does not actually exist. I cannot see it. At all.

On the other hand "Open all files in the list" exists and works perfectly. 

![image](https://user-images.githubusercontent.com/16729806/81831006-2c4fc800-9580-11ea-83c6-5e6b473f8563.png)

"Open selected file" does not make much sense as the file is automatically opened when the item is selected.

Though....

The context menu is broken when TreeView is hosted in the its own activitybar. So will be visitig menus anyway.

**Comment by koansoftware** [comment]
@oleg-shilo you are right, it was a typo.
"Open all files in the list" exists 
BTW it works only after you add the "workbench.editor.enablePreview" property, and set it's value to false.

**Comment by oleg-shilo** [comment]
txs, will have a look
