### ISSUE TITLE
Feature Request: option for alternate names

### ISSUE THREAD

**Issue by mbaas2** [oleg-shilo/Favorites.vscode#15]
I have a few cases where I have favorite files with identical names, but in different folders and I can only distinguish them by checking the others around them (and with a bit of luck ;))

Two suggestions to deal with those cases:

1. onMouseOver show the fully qualified name of a file/folder
2. Add a feature to provide an optional caption, ie   `c:/foo/goo.txt|See what I mean` or  `c:\foo/goo.txt>Maybe this can work?`

**Comment by oleg-shilo** [comment]
Excellent suggestion. Will do.
Option `#1` is impossible though. VSCode has this TreeView flaw - you cannot control the content of the node tootip. Yes, it's hard to imagine but it is true. The feature request exists for years but... the feature is not there.

Will go with option `#2`

**Comment by oleg-shilo** [comment]
Done. 
Will be available in the very next release:

![image](https://user-images.githubusercontent.com/16729806/82753032-e7d8ed80-9e05-11ea-848e-b116d7bf6645.png)

**Comment by mbaas2** [comment]
I got the update - it works perfectly, thanks very much!
