### ISSUE TITLE
Feature request:  Configurable Setting for Favorites Storage

### ISSUE THREAD

**Issue by cooum** [oleg-shilo/Favorites.vscode#16]
Currently, the Favorites are stored in the Folder  C:\Users\{User}\AppData\Roaming\Code\User\favorites.user. 

I usually use VS Code in a portable mode. So Ideally I would like to have the list of Favorites stored in the VSCode folder itself. Alternatively, I would like to have an option to store it at any location I choose. I would prefer not to store any user data in my C: drive.

**Comment by oleg-shilo** [comment]
Good suggestion.
Marked as _enhancement_. Will implement very soon.

**Comment by cooum** [comment]
Thank you. Much Appreciated

**Comment by oleg-shilo** [comment]
Done. 
Please upgrade

**Comment by cooum** [comment]
Thank you, upgraded!

**Comment by ww7** [comment]
In my case I use Workspaces (like projects), would be good to have posibility to use relative pathes to currently opened folder.
For example `./` - current opened folder, `.favorites/` - subfolder in current opened folder.

Also option to set default faforites filename, with what we can point different lists for different projects/workspaces.
For example `<default>/workspace_name.txt` - default named list file at default path.

**Comment by ww7** [comment]
@oleg-shilo 
Can you please extend this feature?
In some cases, would be useful to have separate Favorites for Workspace or a certain folder.

As I understand, currently we have only two choices, <default> or absolute path.

I propose the next options:
* `name` - subfolder from Workspace root or from an opened folder, e.g. `.favorites`
(where favorites lists inside, relative to currently opened folder or Wrofspace root)
* `<default>/<workspace>` - storing at default path in a subfolder with the name of Workspace opened
