### ISSUE TITLE
About hiding <default> list

### ISSUE THREAD

**Issue by getashraf** [oleg-shilo/Favorites.vscode#17]
I use only one favorite list. I want to hide this` <default>` from tree view like the first screenshot in the readme file.
Is it possible?
Thanks for this nice and simple extension.

**Comment by oleg-shilo** [comment]
Right now it is not possible but I will add it as an option.

**Comment by mross** [comment]
Yes, please!

**Comment by oleg-shilo** [comment]
Done. Wil be available in the very next release.
Use `favorites.singleListMode` to control the mode:
![image](https://user-images.githubusercontent.com/16729806/118393937-02464f80-b685-11eb-9136-7ea80ea6fafa.png)
