### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [oleg-shilo/Favorites.vscode#18]
Please add this useful extension to the [Open VSX Registry](https://open-vsx.org/?search=favorites).

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by oleg-shilo** [comment]
Tried. Kinda not impressed with the experience. 

- I am asked to sign a publisher agreement. 
- In one place documentation indicates I need to change the extension license type to Eclipse Public License. In other it says "you can keep it MIT". Though most likely it is documentation mixup. I do not see how the registry can demand a specific licencing. 
- Asked to create Open-VSX. account, and only after that found out that actually I need Eclipse Foundation account instead.
- There is no workflow for unpublishing extensions. One needs to send email and ask the support to do it.
- I see no alternative non-CLI publishing workflow. With VSCode Marketplace I can use web app if CLI does not work for whatever reason. 

Will wait til it becomes more publisher friendly.

**Comment by GitMensch** [comment]
> Tried.

Thank you.

> Kinda not impressed with the experience.

Thank you for the report. I guess is better to report that to open-vsx, at least some of those entries.

> I am asked to sign a publisher agreement.

Yes, as it is with the Visual Studio Marketplace - and when I compare those, I personally like the Eclipse one more.

> In one place documentation indicates I need to change the extension license ...

That is definitely an error. Can you please report this to https://github.com/EclipseFdn/open-vsx.org ?
The extension can have any license, it only has to explicit state it (which is normally done in the repo and with the SPDX identifier in the package.json).
[during the move to Eclipse there was a short period where the agreement said "any open source license" but even that was dropped to the current and final "any license"]

> Asked to create Open-VSX. account, and only after that found out that actually I need Eclipse Foundation account instead.

Please report to the repo above, too.

> There is no workflow for unpublishing extensions. One needs to send email and ask the support to do it.

Interesting. Good to know that there is also that option for unpublishing (I've seen people creating an issue on the above page and it was unpublished so that would be another option).
Can you please explain how this is relevant for you?

> I see no alternative non-CLI publishing workflow.

That's an interesting point, I never thought about this myself.

> Will wait til it becomes more publisher friendly.

Thanks for trying and for listing those issues - can you please create an issue for the above points on the Eclipse repo to allow the publishing to get more publisher-friendly?
