### ISSUE TITLE
FR: Open in new window

### ISSUE THREAD

**Issue by tyler36** [oleg-shilo/Favorites.vscode#19]
Great extension. I really like the multiple lists support.

One thing I would like is the ability to "open folder" in a new window.
Either as a:
- 'Alt+click' on `<Open folder>`
- `right-click`  on `<Open folder>`

Not sure if its possible, but would be nice. 😄

**Comment by oleg-shilo** [comment]
Thank you.
Have marked it as enhancement.

**Comment by tyler36** [comment]
Thank you very much! 

This feature appears in `1.5.1`. Right-click on favorite to reveal "Open in new window" option. Works exactly as requested.

**Comment by oleg-shilo** [comment]
Glad you like it :)
