### ISSUE TITLE
Automatically open Workspace

### ISSUE THREAD

**Issue by davidjamartin** [oleg-shilo/Favorites.vscode#20]
Is it possible to click on a favourite and it automatically open the workspace to avoid the following prompt?

![image](https://user-images.githubusercontent.com/5073402/105971269-3d932300-6082-11eb-824b-0c1b8d2b2eb9.png)

**Comment by davidjamartin** [comment]
The behaviour hasn't changed for me, do I need to store the path to the workspace differently?

If I have the path to the folder, it opens the folder and prompts for the workspace as the screenshot above.
If I have a path to the workspace file it opens the workspace file rather than the workspace.

If it helps I'm on Windows.

**Comment by oleg-shilo** [comment]
Will use this info when working on this issue. Txs
