### ISSUE TITLE
Add icon

### ISSUE THREAD

**Issue by lonix1** [oleg-shilo/Favorites.vscode#21]
By default the extension adds a section to the "Explorer" view.

I dragged it to the activity panel - so now it has its own full panel. But it *uses the same icon as the explorer view* (two pages on top of each other).

Please add an icon to make it stand out?

**Comment by oleg-shilo** [comment]
I am not sure I follow. 
I just dragged it to the activity bar and it seems to have the right icon:
![image](https://user-images.githubusercontent.com/16729806/106590725-8591d880-65a1-11eb-9272-39e49bb0887f.png)

**Comment by oleg-shilo** [comment]
I think I know what happens. In your case the default setting is playing the trick with the IDE.
I will need to have a look at it but for now you can fix it by enabling "Own Explorer" setting: 
![image](https://user-images.githubusercontent.com/16729806/106591400-59c32280-65a2-11eb-9948-3043ea2e7510.png)

**Comment by lonix1** [comment]
Yes it works!! Thanks @oleg-shilo.

LOL small suggestion though... That star icon is not centered, it's right aligned. I know, I know, that's a silly small problem. :stuck_out_tongue:

Thanks for this excellent plugin!

**Comment by oleg-shilo** [comment]
Will have a look :)

Though it is so-o-o-o annoying. I haven't touch this extension for 6 month. I cannot compile it!!! 48 errors

The VSCode API is so volatile that it is 100% guaranteed that even the smallest task as recompiling the codebase (e.g. to update an icon) becomes a task for three evenings :(

And it happens every time I do not touch the extension for some time. It's almost like it's not a good place for stable products.

I love VSCode but this aspect of it is really damaging its image.

**Comment by lonix1** [comment]
This is something I've heard on multiple repos. In many cases devs just recode from scratch a "version 2" than try fix v1.

Frustrating.

**Comment by lonix1** [comment]
Thanks for fixing that. Works nicely.

Remember to "center align" the icon if that's at all possible :smile:

**Comment by oleg-shilo** [comment]
I had a look at alignment issue. VS Code does not support an alignment. It simply takes the icon file ad decides how to render it.
And I see no alignment in the SVG definition of the icon file. So I am not sure what are the options I have to control/fix it.

**Comment by lonix1** [comment]
VSCode is the best, until you hit some weird corner case - and it's always something small, like this!

Thanks for looking into it.

**Comment by lonix1** [comment]
I looked into how another popular extension does it, and it's meant [to be 24x24](https://github.com/Gruntfuggly/todo-tree/blob/master/resources/todo-tree-container.svg), whereas this extension [uses a 16x16](https://github.com/oleg-shilo/Favorites.vscode/blob/master/resources/dark/favorite.svg), and as you can see from the icon itself, it's "right aligned" as in it's physically on the right of the image.

I edited the svg in inkscape: 1) enlarged to 24x24 canvas, 2) enlarged vector to fit, 3) ensured it is centered, 4) minified it.

[favorite-aligned.zip](https://github.com/oleg-shilo/Favorites.vscode/files/5935375/favorite-aligned.zip)

I don't know how to test it as I've never written an extension. It may / may not look good. I hope it works?

**Comment by oleg-shilo** [comment]
You are my friend a hopeless perfectionist. And I absolutely respect (and share) this quality :o)

The update v1.5.1 is available.

**Comment by lonix1** [comment]
Guilty as charged! :stuck_out_tongue:
