### ISSUE TITLE
Provide a way to have toggled lists

### ISSUE THREAD

**Issue by mbaas2** [oleg-shilo/Favorites.vscode#22]
I found that my favs-list got too long, so I split it into several lists, according to topics or categories.
Much better! But now that I'm entered this minimalistic route, I wonder if it possible to open/close "sub-lists" within a list. Basically the same way WSX deals with subfolders. I would really by happy about such an enhancement! 😉

**Comment by oleg-shilo** [comment]
Making it into `Enhancement`
I think technically it can be done.

**Comment by mbaas2** [comment]
Cool - that stirs up hope! 😉

**Comment by oleg-shilo** [comment]
Done. Will be available in the very next release
You can create grouped lists according this pattern: `[group_name.]<list_name>.list.txt`

![image](https://user-images.githubusercontent.com/16729806/118662841-aa018000-b833-11eb-850e-0bf61f07cd64.png)
