### ISSUE TITLE
Feature request: Configurable Favorites Storage

### ISSUE THREAD

**Issue by ww7** [oleg-shilo/Favorites.vscode#23]
In some cases, would be useful to have separate Favorites for Workspace or a certain folder.

As I understand, currently we have only two choices, `<default>` or absolute path.

I propose the next options:
* `name` - subfolder from Workspace root or from an opened folder, e.g. `.favorites` (relatively to current opened folder or Workspace root). If no custom folder exist - use `<default>`. 

* Boolean setting `Separate Favorites for Workspace`, where we can choose if certain Workspace uses separate Favorites (where lists stored in subfolder with Workspace name inside `<default>`, these also can respect "favorites.dataLocation" and use `name`)

**Comment by oleg-shilo** [comment]
Great idea. Txs

**Comment by oleg-shilo** [comment]
Done. Will be available in the very next release
You can create grouped lists according this pattern: `[group_name.]<list_name>.list.txt`

![image](https://user-images.githubusercontent.com/16729806/118662841-aa018000-b833-11eb-850e-0bf61f07cd64.png)

**Comment by lonix1** [comment]
Where does "<default>" save to?

**Comment by oleg-shilo** [comment]
![image](https://user-images.githubusercontent.com/16729806/120784877-e7724700-c56f-11eb-83ab-5362b3a6459c.png)

And then:
![image](https://user-images.githubusercontent.com/16729806/120785118-299b8880-c570-11eb-960f-67fea9ae8527.png)

**Comment by lonix1** [comment]
awesome thanks!

**Comment by ww7** [comment]
How does this work now?

Seems only absolute path and <default> works.

Привет. 
В документации не описано как возможность задания пути хранения работает.
На данный момент только <default> и полный кастомный путь работает?

Я предлагал две идеи для добавления портативности.
1) Возможности разделить фаворитесы для разных воркспейсов. 
Т.е. если задав 
`<workspace>` - сохранит в подпапке с именем воркспейса в папке профиля VSCODE, т.е. по сути будет <default>/<workspace>
Если открыт не workspace - использовать <default>
2) Возможность использовать релятивные пути, т.е. если папку перенести, что бы могло подтягивать из текущей корневой папки
например `.favs` - если в открытой папке/workspace есть подпапка .favs - сохранять туда, если нету - использовать <default>

**Comment by oleg-shilo** [comment]
Hi Serhii,

Sorry, I will stick to English. My Russian is rusty and the rest of the audience will also need to understand the discussion.

Indeed you proposed two options: "I propose the next options:". 
After considering both of them I have decided to chose the first one.

The reason - it is simpler and  consistent with the existing persistence model. 
Splitting the storage into multiple locations is possible but can potentially lead to the confusing user experience (e.g. dealing with nested/grouped lists). 

I hope it explains.

**Comment by ww7** [comment]
Hi Oleg, so how it can be configured additionally to <default> and absolute path?

**Comment by oleg-shilo** [comment]
The description is here:
https://github.com/oleg-shilo/Favorites.vscode#list-definition-rules

But to put it simple, you just create you normal fav list and then simply right-click the list (or any item) and select "associate..." 

![image](https://user-images.githubusercontent.com/16729806/126887279-1dafd968-aa0a-457a-973b-c2c437d87cad.png)

**Comment by oleg-shilo** [comment]
Saying that, if you feel you want to give it a crack with "relative path" feel free to experiment and if you have something working then push the PR and we can have a look at it.

Maybe sacrificing grouping is the way to go. 
May be not hiding the rest of the lists is the compromise to your original proposal that you are prepared to make...

**Comment by ww7** [comment]
Thanks.
Basically, my requests are only around the possibility to use a relative path.
I do not know JS, so maybe I create a new request.

**Comment by oleg-shilo** [comment]
Indeed create a feature request and I will give it a try. 
I am going to revisit all VSCode plugins anyway.

**Comment by oleg-shilo** [comment]
Done.

From v1.5.3 you can use workspace local list local.list.txt in the workspace folder `<workspace>\.fav\`

This list can contain both absolute and relative paths. All relative paths are to be resolved against the workspace folder.
The simplest content of the <workspace>\.fav\local.list.txt:
```txt 
.\.fav\local.list.txt 
```

**Comment by lonix1** [comment]
Usually vscode config goes into `.vscode/`.

Is it maybe possible to save it to `.vscode/fav.local.list.txt` (or similar) as well?

**Comment by oleg-shilo** [comment]
> Usually vscode config goes into...

Not exactly, `.vscode` is not created for open folders (not workspaces).

**Comment by lonix1** [comment]
> .vscode is <strike>not</strike> created for open folders (not workspaces).

I assume my strikeout edit is correct? In that case I don't use the workspace feature, I just open the directory with my code and `.git/`, and I use the `.vscode/` feature.

So I guess I didn't understand this feature, sorry.

(That said, in the future it would be nice to specify `.vscode/`, but it's working well for now, thanks.)

**Comment by lonix1** [comment]
Actually I just [read this](https://code.visualstudio.com/docs/editor/workspaces) which suggests I am indeed using workspaces, but it is a "single-folder workspace", whereas I assume you and the OP were discussing something more complicated than that.

**Comment by oleg-shilo** [comment]
> > .vscode is not created for open folders (not workspaces).
> I assume my strikeout edit is correct?

Yes, you are correct. It was my typo. And I also when I said " this feature is rather experimental as it is very limited" I meant storing the configuration in the local folders.

It is limited because it is not possible to provide a good user experience for adding an opened doc to _global vs local_ list. The same goes for editing. You click "Edit list" button, but which list do you want to edit? The items from both lists are displayed.

It is possible to solve but it requires some strong UX considerations :)

Though since currently the workflow requires manual management of local lists, I sss no problems with extending the support for an alternative naming convention.

The release v1.5.5: https://github.com/oleg-shilo/Favorites.vscode/releases/tag/v1.5.5

Supports an additional local list location: `<workspace/folder>\.vscode\fav.local.list.txt`. As you suggested.

Though I don't want to annoy the users with too frequent updates so di not publish the release on marketplace but only on GitHub and as a pre-release.

**Comment by lonix1** [comment]
That is amazing I'm gonna check it out thanks!

Yes frequent releases annoys me too... there are some plugins that update every second day! :rage:
