### ISSUE TITLE
Sync across machines

### ISSUE THREAD

**Issue by carlocardella** [oleg-shilo/Favorites.vscode#24]
Is it possible to sync the favorite lists across machines?

**Comment by mbaas2** [comment]
If you sync your settings using built-in methods, favorites will be synced as well. I don't think you need to do anything special - worked out of the box, IIRC.

**Comment by carlocardella** [comment]
Odd, I do use the built-in method (all toggles enabled) but favorites are not sync'ed across machines. Maybe I can trace the sync operation, I'll take another look

**Comment by oleg-shilo** [comment]
I haven't try to synch via settings but, yes I would expect it to work. 
You can check your all lists on the source and the destination machines: 
`C:\Users\<user>\AppData\Roaming\Code\User\favorites.user`

If it did not sync :( you can just copy/move the lists. They are just text files after all.

**Comment by carlocardella** [comment]
Favorites are not sync'ed on my machines; also, I have enabled all options to sync everything but there is no "favorites" listed. 
I assume it may be possible using the [Shan Khan extension](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) since it allows to sync custom user files but I would prefer to stay with the buildin sync if possible.

![image](https://user-images.githubusercontent.com/5784415/126872829-f19e8da2-e392-47a8-ba2c-d0d3f4fb8a9c.png)

**Comment by oleg-shilo** [comment]
it's probably quite clear that it there is not much that can be done from the extension to "fix" another extension/built-in product to work correctly or differently. 

I would expect any sync solution to handle all product specific content of the user profile. That's why by default the fav lists are stored there by default:
```ts
    if (os.platform() == 'win32')
        return path.join(process.env.APPDATA, 'Code', 'User', 'favorites.user');
    else if (os.platform() == 'darwin')
        return path.join(process.env.HOME, 'Library', 'Application Support', 'Code', 'User', 'favorites.user');
    else
        return path.join(process.env.HOME, '.config', 'Code', 'User', 'favorites.user');
```
Why it does not pick them it's a mystery for me.
