### ISSUE TITLE
The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by mmapes** [oleg-shilo/Favorites.vscode#25]
On Windows 10. VS Code version 1.60.1., I am stuck on this error: 
![image](https://user-images.githubusercontent.com/246760/133910355-579b0f24-db9d-4036-8396-4cf49064d17c.png)

I have uninstalled and reinstalled the extension. I even uninstalled and reinstalled VS code, then reinstalled the extension, and I still get the same error. 

Any advice on which "path" argument might not be set on a clean Windows install?

(FYI it looks like downgrading to 1.5.2 fixes the issue)

**Comment by oleg-shilo** [comment]
My apologies, I missed this problem. 
The new functionality did not handle the initialization with no Folder/Workspace opened.

Fixed in v1.5.4
