### ISSUE TITLE
Enhancement: Ability to Remove the Default List

### ISSUE THREAD

**Issue by ratkinson-prh** [oleg-shilo/Favorites.vscode#27]
I have a number of list files, e.g. Workspaces, Code Config, etc. I noticed that if I delete 'Default.list.txt' it's automatically recreated. I'm guessing this is mandatory.

Can this be changed so that one of the other lists becomes the default so I can delete the Default list, or even just hide it from the explorer view.

Thanks, Rob.

**Comment by oleg-shilo** [comment]
Done, please update the extension.

Now you can simply rename `Default.list.txt` (e.g. ` My List.list.txt` ) and the name change will be reflected in VSCode:

![image](https://user-images.githubusercontent.com/16729806/146169041-8cd09a38-907e-4ddc-983e-7001d55902ea.png)

**Comment by ratkinson-prh** [comment]
Thanks Oleg, that works great.

Out of interest, I spotted this change in Tree View. Is the question mark intended or a typo?

`items?.forEach(item => {`

**Comment by oleg-shilo** [comment]
:)
It is intended.
If `items` is null there should not be any iterations.
This code is an equivalent of:
```ts
if (items)
    items.forEach(item => {...
```

**Comment by GitMensch** [comment]
Done and released, so can be closed, can't it?

**Comment by ratkinson-prh** [comment]
Apologies for not replying straight away. I tested the change back in December, and it works perfectly thanks.
