### ISSUE TITLE
Show full path on hover (feature request)

### ISSUE THREAD

**Issue by ww7** [oleg-shilo/Favorites.vscode#30]
Show full path with hover popup
And maybe option to show full path in round brackets (truncated)

**Comment by oleg-shilo** [comment]
Agree. Good suggestion

**Comment by oleg-shilo** [comment]
Done
- Added `favorites.maxTooltipLength` configuration value.
  _Maximum length of the favorite item tooltip. Typically file path. If the path length exceeds the maximum value it is displayed truncated._

**Comment by GitMensch** [comment]
Done, so can be closed, can't it?

**Comment by ww7** [comment]
Yes
