### ISSUE TITLE
Chinese file name is garbled, decodeURI() var document  can solve the problem. Maybe other languages have this problem too

### ISSUE THREAD

**Issue by ssr-vpn** [oleg-shilo/Favorites.vscode#32]
modify %USERPROFILE%\.vscode xtensions\oleg-shilo.favorites-1.5.11\out\src xtension.js ,the 65 line,document = decodeURI(vscode.window.activeTextEditor.document.uri.toString());can solve the problem

**Comment by oleg-shilo** [comment]
Thank you, will have a look. Can you please provide a file name here that triggers the problem? So I can test and fix it.

**Comment by ssr-vpn** [comment]
C:\Users\l\OneDrive\sync\workspace\script\bash\bcc\root\生成目录索引页-dir-需行数.sh

**Comment by oleg-shilo** [comment]
Thank you. 
Done. 
Please update your extension to v1.5.12
