### ISSUE TITLE
Suggestion: If 'Data Location' setting is blank, parse it as <default> instead of "favorites.dataLocation": ""

### ISSUE THREAD

**Issue by carloscadux** [oleg-shilo/Favorites.vscode#34]
Hi,

Just a suggestion to avoid an error due to 'Data Location' left blank.

I removed a custom path a had set in the extension 'Data Location' settings, leaving a blank field.

After that the error shown in the screenshot below started appearing.

Later I noticed directly in VSCode settings.json that the extension added the entry `"favorites.dataLocation": "",`

I deleted the entry and notice that the 'Data Location' setting was restored to <default>

Just then I realized that through the settings UI I needed to retype <default> to reset the path.

The suggestion I'm making is aimed to avoid the error because of the blank field, by parsing it as <default>.

Otherwise, I'd suggest leaving a tip under ''Data Location' setting UI, informing the user to type <default> in order to restore the default path.

Thank you!
Carlos

![image](https://user-images.githubusercontent.com/7339389/156257459-2ccfcdce-642c-4987-913c-830d35cc3413.png)

![image](https://user-images.githubusercontent.com/7339389/156257473-040599ea-b47a-49a2-a162-4a35b2787639.png)

**Comment by GitMensch** [comment]
Done, so maybe close?

**Comment by oleg-shilo** [comment]
I usually wait a few days in case of an immediate defect report.
 Seems OK now
