### ISSUE TITLE
Possibility to add a command to open files in the favorite list ?

### ISSUE THREAD

**Issue by xiaoouwang** [oleg-shilo/Favorites.vscode#7]
Very nice plugin sir ! I especially appreciate the fact that all the favorites are accessible in the global space and not specific to projects.

Is it possible to add a command to open files in the favorite list ? that will really be very handy.

Sincerely yours

**Comment by oleg-shilo** [comment]
I am glad you liked it :)

Yes your proposal is a good feature to have. Done:

![image](https://user-images.githubusercontent.com/16729806/53881305-77f70f80-4067-11e9-8149-6f984b5fa712.png)

Will be available in the next release

**Comment by xiaoouwang** [comment]
@oleg-shilo You are fast sir ! I think I didn't make myself clear enough (sorry for my english) actually I suggest a command that will l list the files added in favorite add choose to open from there, thus it's no longer necessary to use a mouse, a little bit in the following way (the command can be something like browse favorite):

![image](https://user-images.githubusercontent.com/16024291/53882054-8e747b00-4015-11e9-8e4b-3112d6cced97.png)

**Comment by oleg-shilo** [comment]
Will need to investigate it.
Txs
