### ISSUE TITLE
Cross-platform usage

### ISSUE THREAD

**Issue by mbaas2** [oleg-shilo/Favorites.vscode#8]
(Disclaimer: I am not sure if this a real issue of Favorites or if I am abusing it or perpahsp just don't know it well enough - so pls. forgive me if the latter should be the case. Would appreciate a few hints in that case ;-))

I have similiar folder-structures for my favs on my Windows-machine and on my Linux-box. Where Win says C:\,Git Linux just uses /Git and all is well. I suppose I could address that with appropriate env-vars.  So I would like to use the same Favs on all platforms.

But I hit a problem with %AppData%Roaming\Code\User\favorites.user\config.json which has a full path to the current list. I tried to replace that full path with "./" which worked. Once - but as soon as the favs were loaded, that path was changed back to a full path - which defeats the purpose I was looking for. So I tried to use EnvVars there - (hoping $ might be a cross-platform-vs-way of using them), but that didn't work either. Is it possible to somehow make that a relative path or use envVars (on Win, *nix and Mac)?

**Comment by oleg-shilo** [comment]
I am not entirely sure about what you are trying to achieve bu you can definitely have envars in your favorite list content:
 
```txt
# The content below is just a Favorites list sample
$CSSCRIPT_DIR/cscs.runtimeconfig.json
```

![image](https://user-images.githubusercontent.com/16729806/54071860-ade5ff00-42c6-11e9-8b88-379b417ea1e3.png)

**Comment by mbaas2** [comment]
It seems I can't specify the path to the list-files with my favs in a cross-platform way.
The file blabla\User\favorites.user\config.json has an absolut path with C:\ in it. That will not work on Linux. So I tried to replace that absolute path with a relative path "./foo.list.txt", but after loading that path was replaced with the absolute path.

**Comment by oleg-shilo** [comment]
> So I tried to replace that absolute path with a relative path "./foo.list.txt"...

OK I see now what you mean. Though it is a very little benefit for the extension to store the fav-list nfile name instead of the path I don't see any particular harm in it. 

Done. 

![image](https://user-images.githubusercontent.com/16729806/54079893-9b58dd80-4339-11e9-823b-73611dff844c.png)

**Comment by mbaas2** [comment]
Great, thanks very much!
